/**
 * Auction Model
 * Represents an auction within a season
 * 
 * Firestore Collection: /auctions
 * Document ID: Auto-generated by Firestore
 * 
 * Parent: Season (via seasonId reference)
 */

export const AuctionSchema = {
  // Foreign key reference
  seasonId: {
    type: String,
    required: true,
    description: 'Reference to parent Season document'
  },
  
  // Core fields
  sport: {
    type: String,
    required: true,
    enum: ['football', 'cricket', 'basketball', 'baseball', 'volleyball'],
    description: 'Sport category (inherited from season)'
  },
  name: {
    type: String,
    required: true,
    description: 'Auction name (e.g., "IPL 2026 Main Auction")'
  },
  
  // Status tracking
  status: {
    type: String,
    enum: ['upcoming', 'live', 'completed'],
    default: 'upcoming',
    description: 'Current auction status'
  },
  
  // Auction details
  participatingTeams: {
    type: Array,
    default: [],
    description: 'Array of team IDs participating in this auction'
  },
  playerPool: {
    type: Array,
    default: [],
    description: 'Array of player IDs available for this auction'
  },
  
  // Auction settings
  settings: {
    minBidIncrement: {
      type: Number,
      default: 100000,
      description: 'Minimum bid increment amount'
    },
    maxPlayersPerTeam: {
      type: Number,
      default: 15,
      description: 'Maximum players per team'
    },
    bidTimeLimit: {
      type: Number,
      default: 30,
      description: 'Bid time limit in seconds'
    }
  },
  
  // Auction scheduling
  scheduledStartTime: {
    type: String, // ISO 8601 format
    required: false,
    description: 'Scheduled auction start time'
  },
  scheduledEndTime: {
    type: String, // ISO 8601 format
    required: false,
    description: 'Scheduled auction end time'
  },
  
  // Auctioneer assignment
  assignedAuctioneerId: {
    type: String,
    required: false,
    description: 'Auctioneer responsible for this auction'
  },
  assignedAuctioneerName: {
    type: String,
    required: false,
    description: 'Auctioneer name for display'
  },
  
  // Statistics
  stats: {
    playersAuctioned: {
      type: Number,
      default: 0
    },
    playersSold: {
      type: Number,
      default: 0
    },
    playersUnsold: {
      type: Number,
      default: 0
    },
    totalSpent: {
      type: Number,
      default: 0
    }
  },
  
  // Audit fields
  createdAt: {
    type: String, // ISO 8601 format
    default: () => new Date().toISOString(),
    description: 'Auction creation timestamp'
  },
  updatedAt: {
    type: String, // ISO 8601 format
    default: () => new Date().toISOString(),
    description: 'Last update timestamp'
  }
};

/**
 * Auction factory function
 */
export const createAuctionDocument = (data) => {
  const now = new Date().toISOString();
  
  return {
    seasonId: data.seasonId,
    sport: data.sport,
    name: data.name,
    status: data.status || 'upcoming',
    participatingTeams: data.participatingTeams || [],
    playerPool: data.playerPool || [],
    settings: {
      minBidIncrement: data.settings?.minBidIncrement || 100000,
      maxPlayersPerTeam: data.settings?.maxPlayersPerTeam || 15,
      bidTimeLimit: data.settings?.bidTimeLimit || 30
    },
    scheduledStartTime: data.scheduledStartTime || null,
    scheduledEndTime: data.scheduledEndTime || null,
    assignedAuctioneerId: data.assignedAuctioneerId || null,
    assignedAuctioneerName: data.assignedAuctioneerName || null,
    stats: {
      playersAuctioned: 0,
      playersSold: 0,
      playersUnsold: 0,
      totalSpent: 0
    },
    createdAt: now,
    updatedAt: now
  };
};
