/**
 * Season Model
 * Represents a sports season (e.g., IPL 2026, Premier League 2026)
 * 
 * Firestore Collection: /seasons
 * Document ID: Auto-generated by Firestore
 */

export const SeasonSchema = {
  // Required fields
  sport: {
    type: String,
    required: true,
    enum: ['football', 'cricket', 'basketball', 'baseball', 'volleyball'],
    description: 'Sport category for this season'
  },
  name: {
    type: String,
    required: true,
    description: 'Season name (e.g., "IPL 2026", "Premier League 2026")'
  },
  year: {
    type: Number,
    required: true,
    description: 'Year of the season'
  },
  
  // Status tracking
  status: {
    type: String,
    enum: ['upcoming', 'active', 'completed'],
    default: 'upcoming',
    description: 'Current status of the season'
  },
  
  // Date fields
  startDate: {
    type: String, // ISO 8601 format
    required: false,
    description: 'Season start date'
  },
  endDate: {
    type: String, // ISO 8601 format
    required: false,
    description: 'Season end date'
  },
  
  // Audit fields
  createdAt: {
    type: String, // ISO 8601 format
    default: () => new Date().toISOString(),
    description: 'Season creation timestamp'
  },
  updatedAt: {
    type: String, // ISO 8601 format
    default: () => new Date().toISOString(),
    description: 'Last update timestamp'
  }
};

/**
 * Composite unique key for Season
 * Ensures only one season per sport per year
 */
export const getSeasonUniqueKey = (sport, year) => {
  return `${sport}_${year}`;
};

/**
 * Season factory function
 */
export const createSeasonDocument = (data) => {
  const now = new Date().toISOString();
  
  return {
    sport: data.sport,
    name: data.name,
    year: data.year,
    status: data.status || 'upcoming',
    startDate: data.startDate || null,
    endDate: data.endDate || null,
    createdAt: now,
    updatedAt: now,
    // Composite key for uniqueness
    uniqueKey: getSeasonUniqueKey(data.sport, data.year)
  };
};
